//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminInfo
    {
        public int AdminInfo_Id { get; set; }
        public string AIAccount { get; set; }
        public string AIPwd { get; set; }
        public string AIName { get; set; }
        public string AIImg { get; set; }
        public Nullable<int> IsSa { get; set; }
    }
}
