//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataList
    {
        public int GoodsInfo_Id { get; set; }
        public string GIName { get; set; }
        public Nullable<int> GoodsType_id { get; set; }
        public Nullable<int> GoodsImgs_id { get; set; }
        public Nullable<double> GIPrice { get; set; }
        public string GIItem { get; set; }
        public Nullable<System.DateTime> GIShangShi { get; set; }
        public string GICPU { get; set; }
        public string GIPingMu { get; set; }
        public string GIFenBianLv { get; set; }
        public string GIHouDu { get; set; }
        public string GIDianChi { get; set; }
        public string GINeiCun { get; set; }
        public Nullable<int> GIKuCun { get; set; }
        public Nullable<int> CIXiaoLiang { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<int> IsHot { get; set; }
        public Nullable<int> IsDown { get; set; }
        public string GIRemark { get; set; }
    }
}
