//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsDetailsIMG
    {
        public int GoodsDetailsIMG1 { get; set; }
        public Nullable<int> GoodsInfo_id { get; set; }
        public string GoodsDetailsIMG_thumbone { get; set; }
        public string GoodsDetailsIMG_thumbtwo { get; set; }
        public string GoodsDetailsIMG_thumbthree { get; set; }
    }
}
