//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsImgs
    {
        public int GImgs_id { get; set; }
        public string GImgs_thumbone { get; set; }
        public string GImgs_thumbtwo { get; set; }
        public string GImgs_thumbthree { get; set; }
        public string GImgs_thumbfour { get; set; }
        public string GImgs_text { get; set; }
    }
}
