//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B2CSystemEntities1 : DbContext
    {
        public B2CSystemEntities1()
            : base("name=B2CSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminInfo> AdminInfo { get; set; }
        public DbSet<Center_Money> Center_Money { get; set; }
        public DbSet<CollectInfo> CollectInfo { get; set; }
        public DbSet<DataList> DataList { get; set; }
        public DbSet<GoodsDetailsIMG> GoodsDetailsIMG { get; set; }
        public DbSet<GoodsImgs> GoodsImgs { get; set; }
        public DbSet<GoodsInfo> GoodsInfo { get; set; }
        public DbSet<GoodType> GoodType { get; set; }
        public DbSet<KeFu> KeFu { get; set; }
        public DbSet<OrderInfo> OrderInfo { get; set; }
        public DbSet<pingjia> pingjia { get; set; }
        public DbSet<Shangjia_X_GoodsInfo> Shangjia_X_GoodsInfo { get; set; }
        public DbSet<ShopCartInfo> ShopCartInfo { get; set; }
        public DbSet<ShouAddress> ShouAddress { get; set; }
        public DbSet<StoreInfo> StoreInfo { get; set; }
        public DbSet<UserDetails> UserDetails { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
