//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCartInfo
    {
        public int SC_Id { get; set; }
        public Nullable<int> GoodsInfo_Id { get; set; }
        public Nullable<int> UserInfo_Id { get; set; }
        public Nullable<System.DateTime> SC_addtime { get; set; }
        public Nullable<double> SC_price { get; set; }
        public Nullable<int> SC_number { get; set; }
        public string Remark { get; set; }
    }
}
